version: "3.8"

networks:
  monitoring:
    name: monitoring
    driver: bridge

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    networks:
      monitoring:
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"